### ISSUE TITLE
install unox fail, `:using => "python@x.y"`

### ISSUE THREAD

**Issue by zljpz** [EugenMayer/docker-sync#754]
### OS
10.15.6 Catelina

I run "brew install eugenmayer/dockersync/unox" meet 

Updating Homebrew...
==> Installing unox from eugenmayer/dockersync
==> Downloading https://pypi.python.org/packages/54/7d/c7c0ad1e32b9f132075967fc353a244eb2b375a3d2f5b0ce612fd96e107e/watchdog-0.8.3.tar.gz
Already downloaded: /Users/zz/Library/Caches/Homebrew/downloads/0d36ce03441bcacec64a81693c6e6cf57ad7388e517415dc3b7512dedf057c03--watchdog-0.8.3.tar.gz
==> Downloading https://pypi.python.org/packages/e7/7f/470d6fcdf23f9f3518f6b0b76be9df16dcc8630ad409947f8be2eb0ed13a/pathtools-0.1.2.tar.gz
Already downloaded: /Users/zz/Library/Caches/Homebrew/downloads/0f7b6eac9aedf76318368c0c3b8cc98e75adbf403b4b1de98260fd84815b31f3--pathtools-0.1.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/11/74/2c151a13ef41ab9fb43b3c4ff9e788e0496ed7923b2078d42cab30622bdf/virtualenv-16.7.4.tar.gz
Already downloaded: /Users/zz/Library/Caches/Homebrew/downloads/507d2087bf24df82641b681a5fe4da778ef50ebe819a86ea1b584f70788f0f63--virtualenv-16.7.4.tar.gz
==> Downloading https://github.com/hnsl/unox/archive/0.2.0.tar.gz
Already downloaded: /Users/zz/Library/Caches/Homebrew/downloads/b2503a5e57457fddcbad2f236a6df2107425dec0ebbf983599a6429f3a5c2f9c--unox-0.2.0.tar.gz
Error: An exception occurred within a child process:
  FormulaUnknownPythonError: The version of Python to use with the virtualenv in the `eugenmayer/dockersync/unox` formula
cannot be guessed automatically because a recognised Python dependency could not be found.

If you are using a non-standard Python depedency, please add `:using => "python@x.y"` to
`virtualenv_install_with_resources` to resolve the issue manually.

Please tell me How to fix ,thx :) ;

python --version : 2.7.16 
python3  -version : 3.8.5

**Comment by EugenMayer** [comment]
Please see https://github.com/EugenMayer/homebrew-dockersync .. specificly https://github.com/EugenMayer/homebrew-dockersync/issues/13

**Comment by zljpz** [comment]
This doesn't look the same problem. emm.... It looks the same as before.

**Comment by zljpz** [comment]
I want to ask, it mean's that , I need to using the correct python version , How I can do this ? thx.

**Comment by bocharsky-bw** [comment]
Faced the same error:
```
==> Downloading https://github.com/hnsl/unox/archive/0.2.0.tar.gz
Already downloaded: /Users/victor/Library/Caches/Homebrew/downloads/b2503a5e57457fddcbad2f236a6df2107425dec0ebbf983599a6429f3a5c2f9c--unox-0.2.0.tar.gz
Error: An exception occurred within a child process:
  FormulaUnknownPythonError: The version of Python to use with the virtualenv in the `eugenmayer/dockersync/unox` formula
cannot be guessed automatically because a recognised Python dependency could not be found.

If you are using a non-standard Python depedency, please add `:using => "python@x.y"` to
`virtualenv_install_with_resources` to resolve the issue manually.
```

Can't install `brew install eugenmayer/dockersync/unox` successfully.

EugenMayer/homebrew-dockersync#13 looks completely different error :/

Any other ideas?

**Comment by zljpz** [comment]
Have you found a solution? 
I have 2 macbook .catelina,
faced the same error @bocharsky-bw

**Comment by gonzaloaune** [comment]
Same thing happened to me after updating to Catalina.

**Comment by zljpz** [comment]
@EugenMayer  for catelina, How to deal with this problem

**Comment by bocharsky-bw** [comment]
@zljpz  nope, no solution yet

**Comment by zljpz** [comment]
@bocharsky-bw @gonzaloaune 
I found a solution.
using "brew edit unox"
modify   `depends_on "python@3"` to `depends_on "python@3.8"`
then run "brew install -s unox" or "brew install --build-from-source unox" can install now

**Comment by EugenMayer** [comment]
Does anybody understand the cause and what we are doing here?i'am neither keen with python i this regard, nor with brew bottles in general. I'am really not sure if i want to keep this entire tap and drag people into this hell, or just say, for docker sync 'please install unox the way you like/can'

In any way, thank you guys for working on this one! Changing python the way you did seems odd to me somehow. 3 should point to whatever 3.x one has installed. And if unox out of some reason needs python >=3.8, which would somewhat suprise me, the  i do not expect 3.8 to be installed this way with let's pyenv


I really need to understand what you guys did to your local python, if you did anything at all. Is this your system python, osx core, troubling you - or a custom user python?

**Comment by gonzaloaune** [comment]
@EugenMayer I had pyenv installed with 3.8, had that happened to me and tried uninstalling and leaving the one that comes with osx and still had the same problem, I never came across to fix it so I just changed to using `native_osx` and works well for me although a bit slower than unison but that really doesn't bother me.

**Comment by zljpz** [comment]
I'm macbook , 10.15.6 Catelina
Install according to documentation
![image](https://user-images.githubusercontent.com/13264284/94675618-95c44d80-034c-11eb-93b6-ad70fe91c693.png)

the pyenv  is installed automatically after run "brew install eugenmayer/dockersync/unox"

**Comment by mhaber-tophat** [comment]
Im pretty sure the issue is just brew stopped distributing `python@3` no? so depends_on is pointing to `python@3` which is a brew package that doesnt exist. Pretty sure brew changed it so you must always specify the minor version

**Comment by bocharsky-bw** [comment]
Yeah, I think you're right! For me `brew search` shows only `python@3.7` and `python@3.8` - so no `python@3` package already. I suppose it should be fixed in the unox formula somehow, not sure about possible BC breaks

**Comment by saml-kounta** [comment]
@EugenMayer This is still an issue, do you think we can get the Python dependency version updated for this formula? 🙏

**Comment by saml-kounta** [comment]
> Please see https://github.com/EugenMayer/homebrew-dockersync .. specificly [EugenMayer/homebrew-dockersync#13](https://github.com/EugenMayer/homebrew-dockersync/issues/13)

@EugenMayer The issue OP is reporting here seems to be this issue instead:
[EugenMayer/homebrew-dockersync#14](https://github.com/EugenMayer/homebrew-dockersync/issues/14)

**Comment by EugenMayer** [comment]
@saml-kounta we are still talking about this PR, right https://github.com/EugenMayer/homebrew-dockersync/pull/15/files

it seems this entire mess is pytho related on all fronts?

I will close this issue and move the discussion to EugenMayer/homebrew-dockersync#14
