### ISSUE TITLE
Relative symlinks messed up after being rsynced

### ISSUE THREAD

**Issue by kylehendricks** [EugenMayer/docker-sync#85]
I have a relative symlink in my source directory at `abc/symlink1` and it points to `../def/symlink1`.  After I start docker-sync and inspect the rsync container (and my container) my symlink now points to `/rsynd-munged/../def/symlink1`

Does [`munge symlinks`](https://download.samba.org/pub/rsync/rsyncd.conf.html) need to be turned off?

**Comment by EugenMayer** [comment]
@kylehendricks am i right, that  --munge-links  can by used as a rsync parameter, not only as a server parameter?

Beside we have to thing about the issues (probably) with  --munge-links , you could add this for you using the sync_args https://github.com/EugenMayer/docker-sync/blob/master/example/docker-sync.yml#L36 for now

Does this help you for now?

**Comment by kylehendricks** [comment]
It looks like the version of rsync on my mac is 2.6.9 which doesn't support the `--munge-symlinks` (or `--no-munge-symlinks`?).

I also saw there is an rsync argument `--remote-option` that I could have used to possibly send `--no-munge-links` to the daemon but that is also not supported on the version of rsync on my mac.

**Comment by EugenMayer** [comment]
@kylehendricks install a better rsync version using brew `brew install rsync` its worth it anyway

those are the options there
```
  -L, --copy-links            transform symlink into referent file/dir
            --copy-unsafe-links     only "unsafe" symlinks are transformed
            --safe-links            ignore symlinks that point outside the tree
            --munge-links           munge symlinks to make them safer
```

**Comment by kylehendricks** [comment]
Updated rsync to 3.1.2 and tried passing `--no-munge-links` and `-M--no-munge-links`.  Still get munging.

**Comment by kylehendricks** [comment]
I ended up working around this by doing `sync_args='-L'` but I'm guessing it would make sense to turn off link munging on the rsync docker.

**Comment by EugenMayer** [comment]
-L resolves the symlinks to files, not keeping them as symlinks. Thats not what you want most probably. 

Do your symlink point at a point the the synced data or on the outer dest-container filesystem?

Nevertheless, we neither use chroot, or anything else. I am not able to see how we can fix this server side for now, feel free to enlighten me :)

**Comment by kylehendricks** [comment]
The symlinks are pointed at data within the volume itself.

Supposedly you can add `munge symlinks = no` in rsyncd.conf to disable it.

**Comment by EugenMayer** [comment]
ah, is it enabled by default? If yes, this makes a lot of sense

**Comment by kylehendricks** [comment]
Here's what the doc says.

"The default is disabled when "use chroot" is on and the inside-chroot path
is "/", otherwise it is enabled."

**Comment by EugenMayer** [comment]
https://github.com/EugenMayer/docker-image-rsyncd/blob/master/run#L36 well we have `use chroot = no` so it should be enabled. Got you on this, created https://github.com/EugenMayer/docker-image-rsyncd/issues/5 will be released soon. Thank for the effort / patience!

**Comment by EugenMayer** [comment]
implemented and fixed with the new rsync image

**Comment by thinkspill** [comment]
I'm still seeing munged symlinks. Has this new rsync image been released? Just loaded today, I have an image apparently created 3 weeks ago, while this fix was in just 2 weeks ago:

```
eugenmayer/rsync           latest              e55b4cffcdec        3 weeks ago         7.366 MB
```

Is there a different image available including this fix, or otherwise, when do you expect this to be released?

Thanks!

**Comment by EugenMayer** [comment]
Hi, if it happened, not by intention.

At least looking on the docker-file https://github.com/EugenMayer/docker-image-rsyncd/blob/master/run#L39 the setting should be there. Not sure what potentially could be wrong. If you like, bull that repo and build the image locally - does it work for you then?

**Comment by thinkspill** [comment]
Yes, building it locally fixes it. It looks like the Docker Hub image just hasn't been updated with the latest.

**Comment by EugenMayer** [comment]
Very odd, i ll try to repush it ASAP, thank you!

**Comment by EugenMayer** [comment]
@thinkspill just pushed a new image - please delete your local image using `docker rmi eugenmayer/rsync` and then start `docker-sync` or `docker-sync-stack` - does this work now?

**Comment by EugenMayer** [comment]
as far as i tested it, it works know
